"""add publishers and publications

Revision ID: 3ecf447ef67d
Revises: 2e4c8f569c97
Create Date: 2026-07-29 12:36:18.039478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ecf447ef67d'
down_revision: Union[str, Sequence[str], None] = '2e4c8f569c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishers_id'), 'publishers', ['id'], unique=False)
    op.create_index(op.f('ix_publishers_name'), 'publishers', ['name'], unique=True)
    op.add_column('publications', sa.Column('publisher_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_publications_publisher_id'), 'publications', ['publisher_id'], unique=False)
    op.create_foreign_key(None, 'publications', 'publishers', ['publisher_id'], ['id'], ondelete='SET NULL')
    op.drop_column('publications', 'publisher')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('publisher', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'publications', type_='foreignkey')
    op.drop_index(op.f('ix_publications_publisher_id'), table_name='publications')
    op.drop_column('publications', 'publisher_id')
    op.drop_index(op.f('ix_publishers_name'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_id'), table_name='publishers')
    op.drop_table('publishers')
    # ### end Alembic commands ###
