from enum import Enum

class OrderStatus(str, Enum):
    REQUEST_RECEIVED = "REQUEST_RECEIVED"
    UNDER_REVIEW = "UNDER_REVIEW"
    INVOICE_SENT = "INVOICE_SENT"
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"
    PROCESSING = "PROCESSING"
    SHIPPED = "SHIPPED"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"